<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">findMatchesForRegex</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required string</value>
    <value>[i] field:0:required regexp</value>
    <value>[o] field:1:optional matches</value>
    <value>[o] field:0:required resultType {"noMatch","matchNoGroups","matchWithGroups"}</value>
    <value>[o] field:1:required groups</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">ZmluYWwgSURhdGFDdXJzb3IgY3JzciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KdHJ5IHsNCglm
aW5hbCBTdHJpbmcgc3RyID0gSURhdGFVdGlsLmdldFN0cmluZyhjcnNyLCAic3RyaW5nIik7DQoJ
aWYgKHN0ciA9PSBudWxsICB8fCAgc3RyLmxlbmd0aCgpID09IDApIHsNCgkJdGhyb3cgbmV3IFNl
cnZpY2VFeGNlcHRpb24oIk1pc3NpbmcsIG9yIGVtcHR5IHBhcmFtZXRlcjogc3RyaW5nIik7DQoJ
fQ0KCWZpbmFsIFN0cmluZyByZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3JzciwgInJlZ2V4cCIp
Ow0KCWlmIChyZSA9PSBudWxsICB8fCAgc3RyLmxlbmd0aCgpID09IDApIHsNCgkJdGhyb3cgbmV3
IFNlcnZpY2VFeGNlcHRpb24oIk1pc3NpbmcsIG9yIGVtcHR5IHBhcmFtZXRlcjogcmVnZXhwIik7
DQoJfQ0KCWZpbmFsIFBhdHRlcm4gcDsNCgl0cnkgew0KCQlwID0gUGF0dGVybi5jb21waWxlKHJl
KTsNCgl9IGNhdGNoIChQYXR0ZXJuU3ludGF4RXhjZXB0aW9uIHBzZSkgew0KCQl0aHJvdyBuZXcg
U2VydmljZUV4Y2VwdGlvbigiSW52YWxpZCBwYXJhbWV0ZXIgKFBhdHRlcm4gc3ludGF4OiByZWdl
eHA9IiArIHJlKTsNCgl9DQoJZmluYWwgTWF0Y2hlciBtID0gcC5tYXRjaGVyKHN0cik7DQoJaWYg
KG0uZmluZCgpKSB7DQoJCWZpbmFsIGludCBjbnQgPSBtLmdyb3VwQ291bnQoKTsNCgkJaWYgKGNu
dCA9PSAwKSB7DQoJCQlqYXZhLnV0aWwuTGlzdDxTdHJpbmc+IG1hdGNoZXMgPSBuZXcgamF2YS51
dGlsLkFycmF5TGlzdDxTdHJpbmc+KCk7DQoJCQltYXRjaGVzLmFkZChtLmdyb3VwKCkpOw0KCQkJ
d2hpbGUobS5maW5kKCkpIHsNCgkJCQltYXRjaGVzLmFkZChtLmdyb3VwKCkpOw0KCQkJfQ0KCQkJ
Ly8JZmluYWwgU3RyaW5nIG1hdGNoR3JvdXBzID0gbS5ncm91cCgpOw0KCQkJSURhdGFVdGlsLnB1
dChjcnNyLCAibWF0Y2hlcyIsIG1hdGNoZXMudG9BcnJheSgpKTsNCgkJICAgIElEYXRhVXRpbC5w
dXQoY3JzciwgInJlc3VsdFR5cGUiLCAibWF0Y2hOb0dyb3VwcyIpOw0KCQl9IGVsc2Ugew0KCQkJ
DQoJCUFycmF5TGlzdCA8U3RyaW5nPiBtYXRjaGVkR3JvdXBzID0gbmV3IEFycmF5TGlzdCA8U3Ry
aW5nPigpOw0KCQlBcnJheUxpc3QgPFN0cmluZz4gbWF0Y2hlcyA9IG5ldyBBcnJheUxpc3QgPFN0
cmluZz4oKTsNCgkJbWF0Y2hlcy5hZGQobS5ncm91cCgwKSk7DQoJCWZvciAoaW50IGkgPSAxOyAg
aSA8PSBjbnQ7ICBpKyspIHsNCgkJCW1hdGNoZWRHcm91cHMuYWRkKG0uZ3JvdXAoaSkpOwkJCQkJ
DQoJCSAJfQ0KCQl3aGlsZSAobS5maW5kKCkpew0KCQkJbWF0Y2hlcy5hZGQobS5ncm91cCgwKSk7
DQoJCQlmb3IgKGludCBpID0gMTsgIGkgPD0gY250OyAgaSsrKSB7CQkJCQkJDQoJCQkJbWF0Y2hl
ZEdyb3Vwcy5hZGQobS5ncm91cChpKSk7CQkJCQkJDQoJCQkgCX0NCgkJCX0JCQkJDQoJCQlJRGF0
YVV0aWwucHV0KGNyc3IsICJncm91cHMiLCBtYXRjaGVkR3JvdXBzLnRvQXJyYXkoKSk7DQoJCQlJ
RGF0YVV0aWwucHV0KGNyc3IsICJtYXRjaGVzIiwgbWF0Y2hlcy50b0FycmF5KCkpOw0KCQkJSURh
dGFVdGlsLnB1dChjcnNyLCAicmVzdWx0VHlwZSIsICJtYXRjaFdpdGhHcm91cHMiKTsNCgkJfQ0K
CX0gZWxzZSB7DQoJCUlEYXRhVXRpbC5wdXQoY3JzciwgInJlc3VsdFR5cGUiLCAibm9NYXRjaCIp
Ow0KCX0JCQ0KCUlEYXRhVXRpbC5yZW1vdmUoY3JzciwgInN0cmluZyIpOw0KCUlEYXRhVXRpbC5y
ZW1vdmUoY3JzciwgInJlZ2V4cCIpOw0KfSBjYXRjaCAoUnVudGltZUV4Y2VwdGlvbiBydGUpIHsN
Cgl0aHJvdyBydGU7DQp9IGNhdGNoIChFcnJvciBlKSB7DQoJdGhyb3cgZTsNCn0gY2F0Y2ggKFNl
cnZpY2VFeGNlcHRpb24gc2UpIHsNCgl0aHJvdyBzZTsNCn0gY2F0Y2ggKFRocm93YWJsZSB0aCkg
ew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0aW9uKHRoKTsNCn0gZmluYWxseSB7DQoJY3Jzci5k
ZXN0cm95KCk7DQp9CQkJCQ0KCQ0K</value>
</Values>
