<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">implSavePipelineToFile</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required pipelineFileName</value>
    <value>[i] field:1:optional ignoredKeys</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">ZmluYWwgSURhdGFDdXJzb3IgY3JzciA9IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KZmluYWwgU3Ry
aW5nIHBpcGVsaW5lRmlsZU5hbWUgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKGNyc3IsICJwaXBlbGlu
ZUZpbGVOYW1lIik7DQppZiAocGlwZWxpbmVGaWxlTmFtZSA9PSBudWxsKSB7DQoJdGhyb3cgbmV3
IE51bGxQb2ludGVyRXhjZXB0aW9uKCJNaXNzaW5nIHBhcmFtZXRlcjogcGlwZWxpbmVGaWxlTmFt
ZSIpOw0KfQ0KaWYgKHBpcGVsaW5lRmlsZU5hbWUubGVuZ3RoKCkgPT0gMCkgew0KCXRocm93IG5l
dyBOdWxsUG9pbnRlckV4Y2VwdGlvbigiRW1wdHkgcGFyYW1ldGVyOiBwaXBlbGluZUZpbGVOYW1l
Iik7DQp9DQpTdHJpbmdbXSBpZ25vcmVkS2V5cyA9IElEYXRhVXRpbC5nZXRTdHJpbmdBcnJheShj
cnNyLCAiaWdub3JlZEtleXMiKTsNCmZpbmFsIE1hcDxTdHJpbmcsT2JqZWN0PiBtYXAgPSBuZXcg
SGFzaE1hcDw+KCk7DQpmaW5hbCBMaXN0PFN0cmluZz4ga2V5cyA9IG5ldyBBcnJheUxpc3Q8Pigp
Ow0KaWYgKGlnbm9yZWRLZXlzICE9IG51bGwpIHsNCglrZXlzLmFkZEFsbChBcnJheXMuYXNMaXN0
KGlnbm9yZWRLZXlzKSk7DQp9DQprZXlzLmFkZCgicGlwZWxpbmVGaWxlTmFtZSIpOw0Ka2V5cy5h
ZGQoImlnbm9yZWRLZXlzIik7DQpmb3IgKFN0cmluZyBzIDoga2V5cykgew0KCW1hcC5wdXQocywg
SURhdGFVdGlsLmdldChjcnNyLCBzKSk7DQoJSURhdGFVdGlsLnJlbW92ZShjcnNyLCBzKTsNCn0N
CmZpbmFsIFBhdGggcGF0aCA9IFBhdGhzLmdldChwaXBlbGluZUZpbGVOYW1lKTsNCmZpbmFsIFBh
dGggZGlyID0gcGF0aC5nZXRQYXJlbnQoKTsNCnRyeSB7DQoJRmlsZXMuY3JlYXRlRGlyZWN0b3Jp
ZXMoZGlyKTsNCgl0cnkgKE91dHB1dFN0cmVhbSBvcyA9IEZpbGVzLm5ld091dHB1dFN0cmVhbShw
YXRoKTsNCgkJIEJ1ZmZlcmVkT3V0cHV0U3RyZWFtIGJvcyA9IG5ldyBCdWZmZXJlZE91dHB1dFN0
cmVhbShvcykpIHsNCgkJbmV3IElEYXRhWE1MQ29kZXIoKS5lbmNvZGUoYm9zLCBwaXBlbGluZSk7
DQoJfQ0KfSBjYXRjaCAoSU9FeGNlcHRpb24gZSkgew0KCXRocm93IG5ldyBTZXJ2aWNlRXhjZXB0
aW9uKGUpOw0KfQ0KLy8gUmVzdG9yZSB0aGUgcGlwZWxpbmUgY29udGVudHMNCmZvciAoTWFwLkVu
dHJ5PFN0cmluZyxPYmplY3Q+IGVuIDogbWFwLmVudHJ5U2V0KCkpIHsNCglmaW5hbCBPYmplY3Qg
diA9IGVuLmdldFZhbHVlKCk7DQoJaWYgKHYgIT0gbnVsbCkgew0KCQlJRGF0YVV0aWwucHV0KGNy
c3IsIGVuLmdldEtleSgpLCB2KTsNCgl9DQp9CQkJDQo=</value>
</Values>
