<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">createPipelineFileName</value>
  <array name="sig" type="value" depth="1">
    <value>[i] field:0:required fileNamePrefix</value>
    <value>[i] field:0:optional fileNameSuffix</value>
    <value>[i] field:0:required serviceName</value>
    <value>[i] field:0:optional addTimestamp</value>
    <value>[o] field:0:required pipelineFileName</value>
  </array>
  <value name="sigtype">java 3.5</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gSW5wdXQgcGFyYW1ldGVycw0KZmluYWwgSURhdGFDdXJzb3IgY3JzciA9IHBpcGVsaW5lLmdl
dEN1cnNvcigpOw0KZmluYWwgU3RyaW5nIHN1YkZvbGRlciA9IElEYXRhVXRpbC5nZXRTdHJpbmco
Y3JzciwgInN1YkZvbGRlciIpOw0KZmluYWwgU3RyaW5nIGZpbGVOYW1lU3VmZml4ID0gSURhdGFV
dGlsLmdldFN0cmluZyhjcnNyLCAiZmlsZU5hbWVTdWZmaXgiKTsNCmZpbmFsIFN0cmluZyBzZXJ2
aWNlTmFtZSA9IElEYXRhVXRpbC5nZXRTdHJpbmcoY3JzciwgInNlcnZpY2VOYW1lIik7DQppZihz
ZXJ2aWNlTmFtZSA9PSBudWxsKSB7DQoJdGhyb3cgbmV3IE51bGxQb2ludGVyRXhjZXB0aW9uKCJN
aXNzaW5nIHBhcmFtZXRlcjogc2VydmljZU5hbWUiKTsNCn0NCmlmKHNlcnZpY2VOYW1lLmxlbmd0
aCgpID09IDApIHsNCgl0aHJvdyBuZXcgSWxsZWdhbEFyZ3VtZW50RXhjZXB0aW9uKCJFbXB0eSBw
YXJhbWV0ZXI6IHNlcnZpY2VOYW1lIik7DQp9DQpmaW5hbCBib29sZWFuIGFkZFRpbWVzdGFtcCA9
IElEYXRhVXRpbC5nZXRCb29sZWFuKGNyc3IsICJhZGRUaW1lc3RhbXAiLCBmYWxzZSk7DQoNCi8v
IENyZWF0ZSB0aGUgZmlsZSBuYW1lLg0KZmluYWwgU3RyaW5nQnVpbGRlciBzYiA9IG5ldyBTdHJp
bmdCdWlsZGVyKCk7DQpzYi5hcHBlbmQoInBpcGVsaW5lLyIpOw0KaWYgKHN1YkZvbGRlciAhPSBu
dWxsKSB7DQoJc2IuYXBwZW5kKHN1YkZvbGRlcik7DQoJaWYgKHN1YkZvbGRlci5sZW5ndGgoKSA+
IDAgICYmICAhc3ViRm9sZGVyLmVuZHNXaXRoKCIvIikpIHsNCgkJc2IuYXBwZW5kKCcvJyk7DQoJ
fQ0KfQ0Kc2IuYXBwZW5kKHNlcnZpY2VOYW1lLnJlcGxhY2UoJzonLCAnLicpKTsNCmlmIChmaWxl
TmFtZVN1ZmZpeCAhPSBudWxsICAmJiAgZmlsZU5hbWVTdWZmaXgubGVuZ3RoKCkgPiAwKSB7DQoJ
c2IuYXBwZW5kKCctJyk7DQoJc2IuYXBwZW5kKGZpbGVOYW1lU3VmZml4KTsNCn0NCmlmIChhZGRU
aW1lc3RhbXApIHsNCglsb25nIGwgPSBTeXN0ZW0uY3VycmVudFRpbWVNaWxsaXMoKTsNCglzeW5j
aHJvbml6ZWQocHJldmlvdXNUaW1lc3RhbXBMb2NrKSB7DQoJCWlmIChwcmV2aW91c1RpbWVzdGFt
cCA9PSAwICB8fCAgcHJldmlvdXNUaW1lc3RhbXAgPCBsKSB7DQoJCQlwcmV2aW91c1RpbWVzdGFt
cCA9IGw7DQoJCX0gZWxzZSB7DQoJCQlsID0gcHJldmlvdXNUaW1lc3RhbXArKzsNCgkJfQ0KCQlJ
bnN0YW50IGluc3RhbnQgPSBJbnN0YW50Lm9mRXBvY2hNaWxsaShsKTsNCgkJTG9jYWxEYXRlVGlt
ZSBsZHQgPSBMb2NhbERhdGVUaW1lLm9mSW5zdGFudChpbnN0YW50LCBab25lSWQuc3lzdGVtRGVm
YXVsdCgpKTsNCgkJc2IuYXBwZW5kKCctJyk7DQoJCXNiLmFwcGVuZCh0aW1lc3RhbXBGb3JtYXR0
ZXIuZm9ybWF0KGxkdCkpOw0KCX0NCn0NCnNiLmFwcGVuZCgiLnhtbCIpOw0KSURhdGFVdGlsLnB1
dChjcnNyLCAicGlwZWxpbmVGaWxlTmFtZSIsIHNiLnRvU3RyaW5nKCkpOw0KDQoJDQoJDQoJDQo=
</value>
</Values>
